### ISSUE TITLE
[Error] Crash In V7.0.0

### ISSUE THREAD

**Issue by ZornHadNoChoice** [Hamza417/Peristyle#130]
### Confirmation

- [x] I have read the [Code of Conduct](https://github.com/Hamza417/Peristyle/blob/master/CODE_OF_CONDUCT.md)
- [x] I have searched the existing issues

### Error Description

The entire new Live Auto  Wallpaper feature is not working for me and all I get is a black wallpaper when I tap "Live Auto Wallpaper".

### Steps to Reproduce

1. Tap the Live Wallpapers button in the home screen (the one next to the Folders button).
2. Select Live Auto Wallpaper.
3. Tap Live Auto Wallpaper.
4. Tap Set wallpaper in the Live Wallpaper Picker android app.
5. Select Home screen.
6. Return to Peristyle.

### Expected Behavior

No crash lol.

### Error Logs

java.lang.RuntimeException: Unable to start service app.simple.peri.services.LiveAutoWallpaperService@cffa972 with Intent { act=action.PREVIEW_WALLPAPER cmp=app.simple.peri/.services.LiveAutoWallpaperService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4864)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2254)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at java.lang.Class.isAssignableFrom(Class.java:890)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4853)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4766)
	at android.os.Parcel.readValue(Parcel.java:4532)
	at android.os.Parcel.readValue(Parcel.java:4312)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4410)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4369)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
	at android.os.BaseBundle.getValue(BaseBundle.java:374)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.BaseBundle.get(BaseBundle.java:696)
	at android.os.Bundle.getParcelable(Bundle.java:947)
	at android.content.Intent.getParcelableExtra(Intent.java:8927)
	at androidx.activity.ComponentDialog$$ExternalSyntheticApiModelOutline0.m$2(SourceFile:1)
	at app.simple.peri.services.LiveAutoWallpaperService.onStartCommand(SourceFile:51)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4846)
	... 9 more

### Device Information

Device: POCO F5 PRO ; OS Android 13.

### Additional Context

It seems like the Wallpaper Manager API options does nothing after this crash. Tapping Next Wallpaper does nothing. However, I can still change the wallpaper using the Set as Wallpaper button.

### Sufficiency Confirmation

- [x] I have provided all the information requested above and deemed sufficient for the developer to address the issue

**Comment by frfeed123** [comment]
Same thing happens here.
Samsung Galaxy A17, Android 13

**Comment by Hamza417** [comment]
This error report is identical to the #129 one you posted earlier. I think this is an OS issue and possibly caused by using a custom rom.

**Comment by frfeed123** [comment]
I run the default samsung ROM non-rooted.

**Comment by Hamza417** [comment]
> I run the default samsung ROM non-rooted.

I was referring to the original report posted in the issue. Did you encounter the same crash or a different error/bug?

**Comment by frfeed123** [comment]
Full on identical crash and bug.

**Comment by frfeed123** [comment]
As said.
Auto wallpaper don't work.
Live wallpaper mode crashes.
Manually setting Wallpaper works.

**Comment by Hamza417** [comment]
I found the issue, I'll publish a fix by tonight.

**Comment by frfeed123** [comment]
Okay. Thanks :3

**Comment by ZornHadNoChoice** [comment]
> This error report is identical to the [#129](https://github.com/Hamza417/Peristyle/issues/129) one you posted earlier. I think this is an OS issue and possibly caused by using a custom rom.

I fail to see how they are related, but you have the know-how.

Also, no I'm not using any custom roms and my device isn't rooted.

**Comment by Hamza417** [comment]
I have published a pre-release with the fix. Let me know if it fixes the issues for you guys.

https://github.com/Hamza417/Peristyle/releases/tag/v7.0.1-rc1

**Comment by frfeed123** [comment]
Auto wallpaper works again.
Live wallpaper gives me an black wallpaper and breaks auto wallpaper again.

**Comment by frfeed123** [comment]
Auto wallpaper works again after force closing peri via settings.

**Comment by ZornHadNoChoice** [comment]
There is an improvement but it's still buggy.

When I tap the circular Live Wallpapers button then tap the Live Auto Wallpaper button one of the following can happen:
A. The app crashes and the wallpaper gets set to the device's default wallpaper.
B. The Live Wallpaper Picker is opened but after tapping Set wallpaper, then Home screen, a black wallpaper is set. Also, the Live Wallpaper Picker remains in the recent apps and when I reopen it the app crashes.
C. If after the Live Wallpaper Picker is opened, you go back and swipe the app from the recent apps and tap the Live Auto Wallpaper button again the app crashes.

The good news is that after setting a wallpaper manually, the automatic wallpaper changer starts working again. Also, I'm not sure but I think like a few minutes after crash C the wallpaper starts auto changing again.

```
java.lang.RuntimeException: Unable to start service app.simple.peri.services.LiveAutoWallpaperService@9ea5a3 with Intent { act=action.PREVIEW_WALLPAPER cmp=app.simple.peri/.services.LiveAutoWallpaperService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4864)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2254)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at java.lang.Class.isAssignableFrom(Class.java:890)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4853)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4766)
	at android.os.Parcel.readValue(Parcel.java:4532)
	at android.os.Parcel.readValue(Parcel.java:4312)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4410)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4369)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
	at android.os.BaseBundle.getValue(BaseBundle.java:374)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.BaseBundle.get(BaseBundle.java:696)
	at android.os.Bundle.getParcelable(Bundle.java:947)
	at android.content.Intent.getParcelableExtra(Intent.java:8927)
	at androidx.activity.ComponentDialog$$ExternalSyntheticApiModelOutline0.m$2(SourceFile:1)
	at app.simple.peri.services.LiveAutoWallpaperService.onStartCommand(SourceFile:51)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4846)
	... 9 more
```

**Comment by Hamza417** [comment]
Thanks for the report, I am a bit occupied at the home lately, I will look into it as soon as I get the time to do so.

**Comment by Hamza417** [comment]
> Link to videos: https://mega.nz/folder/JYVgDBKR#sGJsnJKq5CnbDWo_wWj8Rw 

@frfeed123 has there been any crash when using live wallpaper mode?

**Comment by frfeed123** [comment]
It did once but didn't replicate when i made the video.

**Comment by frfeed123** [comment]
nvm managed to replicate it

java.lang.RuntimeException: Unable to start service app.simple.peri.services.LiveAutoWallpaperService@ac4d2f7 with Intent { act=action.PREVIEW_WALLPAPER cmp=app.simple.peri/.services.LiveAutoWallpaperService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5261)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2447)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at java.lang.Class.isAssignableFrom(Class.java:890)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4865)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4778)
	at android.os.Parcel.readValue(Parcel.java:4544)
	at android.os.Parcel.readValue(Parcel.java:4324)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
	at android.os.BaseBundle.getValue(BaseBundle.java:374)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.BaseBundle.get(BaseBundle.java:696)
	at android.os.Bundle.getParcelable(Bundle.java:947)
	at android.content.Intent.getParcelableExtra(Intent.java:9558)
	at androidx.activity.ComponentDialog$$ExternalSyntheticApiModelOutline0.m$2(SourceFile:1)
	at app.simple.peri.services.LiveAutoWallpaperService.onStartCommand(SourceFile:51)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5243)
	... 9 more

**Comment by ZornHadNoChoice** [comment]
Currently the wallpaper is changing automatically as expected, but I can't tell which method it's using. Maybe make that more clear?

**Comment by Hamza417** [comment]
> but I can't tell which method it's using. Maybe make that more clear?

The automatically picks the settings for each mode, I mean theoretically it should. I have probably fixed the parcel issue and currently rechecking everything. Expect the rc2 by midnight UTC.

**Comment by Hamza417** [comment]
I have pushed a new release. Please check everything and let me know the results.

https://github.com/Hamza417/Peristyle/releases/tag/v7.0.2-rc2

**Comment by frfeed123** [comment]
live is still broken with a blackscreen

**Comment by ZornHadNoChoice** [comment]
Sorry for the low recording quality!
https://github.com/user-attachments/assets/e17eb3fa-83d3-473e-8808-cd70dbb54340

**Comment by Hamza417** [comment]
I pushed a new update that should fix the black screen issue.

https://github.com/Hamza417/Peristyle/releases/tag/v7.0.3-rc3

**Comment by frfeed123** [comment]
still somehow "crashed" BUT it works :3

Log:
java.lang.IllegalArgumentException: canvas object must be the same instance that was previously returned by lockCanvas
	at android.view.Surface.unlockSwCanvasAndPost(Surface.java:485)
	at android.view.Surface.unlockCanvasAndPost(Surface.java:478)
	at com.android.internal.view.BaseSurfaceHolder.unlockCanvasAndPost(BaseSurfaceHolder.java:226)
	at app.simple.peri.services.LiveAutoWallpaperService$LiveAutoWallpaperEngine.onSurfaceRedrawNeeded(SourceFile:110)
	at android.service.wallpaper.WallpaperService$Engine.updateSurface(WallpaperService.java:1664)
	at android.service.wallpaper.WallpaperService$Engine.reportVisibility(WallpaperService.java:1902)
	at android.service.wallpaper.WallpaperService$Engine.doVisibilityChanged(WallpaperService.java:1872)
	at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:2842)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by Hamza417** [comment]
So the live wallpaper is working now?

**Comment by frfeed123** [comment]
it is. but after applying it the app crashes once but wallpaper keeps changing nonetheless

**Comment by Hamza417** [comment]
This should fix the above crash as well.

https://github.com/Hamza417/Peristyle/releases/tag/v7.0.4-rc4

**Comment by ZornHadNoChoice** [comment]
Weirdly, I did not have any crashes in v7.0.3 (at least related to the current issue). Unfortunately, It's still buggy. No black screens anymore and it seems that after randomly pressing buttons (or waiting?) the Live Auto Wallpaper starts to work again. But then it easily stops working after pressing the Live Auto Wallpaper button and setting the wallpaper to the home screen.

**Comment by frfeed123** [comment]
new issue
![Screenshot_20250202_183209_Peristyle.jpg](https://github.com/user-attachments/assets/60b3c556-40f5-4999-b989-f4d54e067ceb)

wallpaper list not loading and if i click a category the pics dont load either

**Comment by Hamza417** [comment]
> new issue ![Screenshot_20250202_183209_Peristyle.jpg](https://github.com/user-attachments/assets/60b3c556-40f5-4999-b989-f4d54e067ceb)
> 
> wallpaper list not loading and if i click a category the pics dont load either

You need to open a new issue for each problems, not comment on one.

**Comment by svendsvin** [comment]
Happened for me as well. Using default Motorola phone not rooted. The update fixed it. Here is crash log if useful:

java.lang.NullPointerException
	at app.simple.peri.services.LiveAutoWallpaperService$$ExternalSyntheticLambda1.handleMessage(SourceFile:26)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:362)
	at android.app.ActivityThread.main(ActivityThread.java:8393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)

**Comment by Hamza417** [comment]
I have been using the live wallpaper mode as default mode in my devices for the past week and did not experience any crashes. Are you sure the crash is happening because of the live wallpaper?

**Comment by svendsvin** [comment]
No. Sorry for the confusion. I never use live wallpaper.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Hamza417** [comment]
> at app.simple.peri.services.**LiveAutoWallpaperService**$$ExternalSyntheticLambda1.handleMessage(SourceFile:26)

The error indicates the crash is happening in LiveAutoWallpaperService?

**Comment by ZornHadNoChoice** [comment]
> Weirdly, I did not have any crashes in v7.0.3 (at least related to the current issue).

This is still true with v7.0.4-rc4 which I have been using since it was released. However, I noticed that the Wallpaper Manager API's Next Wallpaper button isn't working:
https://github.com/user-attachments/assets/cb0764d5-b853-44ad-8437-76eba5daf630

However, I just tested it again after recording this video and it now works! I still think there should be a clear indication of what the current method is being used, like a toggle in the settings.

**Comment by Hamza417** [comment]
> However, I noticed that the Wallpaper Manager API's Next Wallpaper button isn't working:

Next Wallpaper button is designed to take on the currently running service. If Live Wallpaper is running, it will use live wallpaper to set the next wallpaper, not the system one. Different phones manage live wallpaper services differently, so it's difficult to make sure which is running when. You set the wallpaper at home screen is the live wallpaper running at lock screen. Android system doesn't exclusively allow live wallpaper on Lock Screens, so make sure the Live Wallpaper service is not running before using system wallpaper manager.

**Comment by Hamza417** [comment]
Adding to the above comment, in some devices you'd need to kill the app or restart the device to effectively rid of any live wallpaper service instances.

**Comment by ZornHadNoChoice** [comment]
> is the live wallpaper running at lock screen.

The lock screen wallpaper is not changed. You can see in the video above that the Lock Screen option is disabled.

**Comment by Hamza417** [comment]
It was a guess, I just found out that changing wallpaper won't automatically stop the LiveWallpaperService, it only destroys the surface. Working on a fix..

**Comment by Hamza417** [comment]
I have fixed the issue as well, if you manually set a wallpaper through the app, it stops the live wallpaper and automatically switches to system wallpaper manager API. This should deal with the next wallpaper not working issue.

**Comment by ZornHadNoChoice** [comment]
> it stops the live wallpaper and automatically switches to system wallpaper manager API.

Isn't this unintuitive? Some features only work with the Live Auto Wallpaper method so users might get confused. Maybe add a little warning message or something?

**Comment by Hamza417** [comment]
> > it stops the live wallpaper and automatically switches to system wallpaper manager API.
> 
> Isn't this unintuitive? Some features only work with the Live Auto Wallpaper method so users might get confused. Maybe add a little warning message or something?

It is, but both services serve different purpose, but we are currently using them to perform the same tasks and this introduces some limitations that cannot be circumvented without doing too much workaround. Refer to the issue #122, it's the main reason why Live Wallpaper mode is added, to eliminate the slow wallpaper change issue which WallpaperManager API has. It's up to the user to decide what works best for them.

Also, features like #23 won't work with WallpaperManager API, but with live wallpaper it can without any extra system load or delay.

**Comment by ZornHadNoChoice** [comment]
I think you misunderstood. What I meant is when the method changes automatically upon setting the wallpaper manually, some features will stop working and users will be coming here reporting "bugs". I suggest adding a warning when setting a wallpaper manually to let the user know.

**Comment by Hamza417** [comment]
I'll think of something for this once I fix the other issues with the live wallpaper. Once everything is working smoothly, then I'll decide what setting a new wallpaper should do in this scenario.

**Comment by Hamza417** [comment]
I think I have fixed most of the crashes now and live wallpaper is working smoothly. Please test the new APK and let me know if you encounter any crashes or issues with live wallpaper.

https://github.com/Hamza417/Peristyle/releases/tag/v7.0.1-rc5

**Comment by ZornHadNoChoice** [comment]
https://youtu.be/v7OqAc-hpEM

Github kept failing to upload the video, so I uploaded it to YouTube.

In the video, you can see first that the wallpaper doesn't change no matter what, then I wait for a whole minute with no change. Finally, I set the wallpaper manually and it starts working properly again. No crashes.

**Comment by Hamza417** [comment]
Thanks, I think a kill switch for live wallpaper should be there to restart the wallpaper service in situations like this. Another issue is I'm aware of is surface release, the live wallpaper releases the surface instance in some scenario, and then it's up to the launcher or in general OS to recreate it when required and when that happens the wallpaper change wouldn't work. I am still working on it, but it's an entirely different issue.

Another issue which you mentioned to add warning setting wallpaper manually, I will simply use the live wallpaper to set the wallpaper instead of using the System Wallpaper Manager. Automatically stopping the service is not the way.

I am merging the PR and this issue will be closed now. Any minor issues will be fixed eventually as the development progresses. Thanks everyone for testing for this issue :)
