### ISSUE TITLE
[Error] 0x0

### ISSUE THREAD

**Issue by ZornHadNoChoice** [Hamza417/Peristyle#156]
### Confirmation

- [x] I have read the [Code of Conduct](https://github.com/Hamza417/Peristyle/blob/master/CODE_OF_CONDUCT.md)
- [x] I have searched the existing issues

### Error Description

This is different from #152.

### Steps to Reproduce

1. Use the Wallpaper Manager (e.g. set a wallpaper manually).
2. Close the app and reopen it.
3. You get this:
![Image](https://github.com/user-attachments/assets/3f786173-1841-4167-9758-9d0a3cccd86d)

### Expected Behavior

obvious.

### Error Logs

N/A.

### Device Information

Device: POCO F5 Pro; OS: Android 13.

### Additional Context

May be caused by the patch in #153.

### Sufficiency Confirmation

- [x] I have provided all the information requested above and deemed sufficient for the developer to address the issue

**Comment by Hamza417** [comment]
Fixed in #115

**Comment by ZornHadNoChoice** [comment]
> Fixed in [#115](https://github.com/Hamza417/Peristyle/issues/115)

But this bug still happens in the version you released in https://github.com/Hamza417/Peristyle/issues/153#issuecomment-2672586135!

**Comment by Hamza417** [comment]
It was fixed in https://github.com/Hamza417/Peristyle/commit/eaeb7f667a9c4179311bb7de0272d7a8865597b5 an hour ago and I have not uploaded any build for this.

**Comment by Hamza417** [comment]
You can also test this error in the build I just uploaded and reopen this issue if you encounter it. I have doubts that it's not fixed yet.

**Comment by ZornHadNoChoice** [comment]
Your doubts are right. It still exists.

**Comment by ZornHadNoChoice** [comment]
So I don't why or how but this bug is fixed in the build you uploaded here https://github.com/Hamza417/Peristyle/issues/159#issuecomment-2675349326

**Comment by Hamza417** [comment]
It is fixed actually, the issue was caused by wiping the whole database instead of just the memory database, leading to empty images. I fixed that which fixed it. I am closing this issue.

**Comment by ZornHadNoChoice** [comment]
> I fixed that which fixed it.

That's a funny sentence :).
